version: '3.8'

services:
  mcp-document-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-document-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # 可以直接在这里设置环境变量
      - PROTOCOL=${PROTOCOL:-http}
      - HOST=${HOST:-localhost}
      - PORT=${PORT:-3000}
      - BASEPATH=${BASEPATH:-/md-to-doc}
      - FILE_EXPIRY_MINUTES=${FILE_EXPIRY_MINUTES:-30}
      - CLEANUP_INTERVAL_MINUTES=${CLEANUP_INTERVAL_MINUTES:-5}
    # 或者使用外部环境文件（优先级更高）
    env_file:
      - .env  # 默认环境文件
      # - production.env  # 生产环境文件（如果存在）
    volumes:
      # 挂载下载目录到宿主机（可选）
      - ./downloads:/app/downloads
      # 挂载临时目录到宿主机（可选）
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # 如果需要SSL证书
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mcp-document-service
    restart: unless-stopped
    profiles:
      - nginx  # 只有使用 --profile nginx 时才启动
